phrase:
  project_id: f6a3d2ae13a8aed9e95ff710b142db25

  push:
    sources:
      - file: ./res/values/strings.xml
        params:
          file_format: xml
          locale_id: en
          update_translation: true
          autotranslate: true
          skip_unverification: false
          tags: strings

  pull:
    targets:
      - file: ./res/values-<locale_name>/<tag>.xml
        params:
          tags: strings
          file_format: xml
